config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  resources :orders, except: [:index, :show]
  devise_for :users
  resources :products do
    resources :reviews, except: [:index]
  end
  resources :cities do
    get 'search', on: :collection
  end

  get 'add_to' => "cities#add_to"
  delete 'delete' => "cities#delete"

  resources :line_items, except: [:index]
  resources :carts, except: [:index]
  resources :categories 
  root 'products#index'


 
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  # default_scope { where(joins(:line_items).order('line_items.quantity')) }
  
def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
      current_item.price = current_item.product.price
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  respond_to :js


  def show
    respond_with(@cart)
  end

  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    respond_with(@cart = Cart.create(cart_params))
  end

  def update
    @cart.update(cart_params)
    respond_with(@cart)
  end

  def destroy
    @cart.destroy
    redirect_to root_url
  end

  private

    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_url, notice: 'Invalid cart'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
  
end

app/views/carts/_form_cart.html.erb
<div id="line">
  <h2>Your Cart</h2>
  <div class="col-md-7">
    <table class="table table-bordered table-striped">
      <tr>
        <th>Name:</th>
        <th>Price:</th>
        <th>Quantity:</th>
        <th>Delete:</th>
    </tr>
    <% cart.line_items.each do |item| %>
      <tr id="item_<%= item.id %>">
        <td><h4><%= item.product.title %></h4></td>
        <td><h4><%= number_to_currency(item.total_price) %></h4></td>
        <td><%= render 'carts/form_line', quantity: item %></td>
        <td><%= button_to "Delete", line_item_path(item) , method: :delete, data: { confirm: "Are you sure?", }, :class => 'btn-custom2' %></td>
        </tr>
    <% end %>
    </table>
    <p><%= button_to 'Empty cart', @cart, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn-custom2' %></p>
  </div>
  <div class="col-md-4">
    <div class="total_price">
    <div class="text-center">
       <p><%= link_to 'Continue Shops', root_path, :class => 'btn-custom' %></p>
      <h3>Total price:</h3>
      <h3><%= number_to_currency(@cart.total_price) %></h3></br>
      <%= link_to "Checkout", new_order_path, :class => 'btn-custom' %></br>     
    </div>
    </div>
  </div>

</div>

app/views/carts/_form_line.html.erb
<%= simple_nested_form_for quantity, remote: true do |f| %>
  <%= f.input :quantity, :input_html => { :style => 'width: 90px', min: 1 }, label: false %>
  <%= f.button :submit, 'Update', :class => 'btn-custom2' %> 
<% end %>

app/views/carts/show.html.erb
<div class="row">
  <%= render 'carts/form_cart', cart: @cart %> 
</div>

app/views/carts/show.js.erb
$('#line').html('<%= j render 'carts/form_cart', cart: @cart %>');
$('#test').html('<%= j render 'layouts/cart_text' %>');
$('#test, .total_price, .cart-top').css({'color':'#f1c40f'}).animate({'color':'#114411'}, 1500);