config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  resources :orders, except: [:index, :show]
  devise_for :users
  resources :products do
    resources :reviews, except: [:index]
  end
  resources :cities do
    get 'search', on: :collection
  end

  get 'add_to' => "cities#add_to"
  delete 'delete' => "cities#delete"

  resources :line_items, except: [:index]
  resources :carts, except: [:index]
  resources :categories 
  root 'products#index'


 
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set
  include TheSortableTree::Scopes

  default_scope -> { order 'lft ASC' } 
  has_many :products

  validates :name, presence: true

  before_destroy :ensure_not_referenced_by_any_product
  before_update :ensure_not_referenced_by_any_product

  def ensure_not_referenced_by_any_product
    if products.empty?
      return true
    else
      errors.add(:message, 'This Category has got products')
      return false
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :find_categoty, only: [:edit, :update, :destroy, :show]
  before_action :authenticate_user!
  before_action :categories_load, only: [:new, :create, :edit, :update]

  include TheSortableTreeController::Rebuild

  def show
    
  end

  
  def index
    clieint_ip = remote_ip
    @country_name = User.found_country(clieint_ip)
    @categories = Category.nested_set.all
  end
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path 
    else
      render :new
    end
  end

  def edit
  end

  def show
   
  end

  def update
    @category.update(category_params)
    respond_with(@category)do |format|
      format.html { redirect_to categories_path }
    end
  end

  def destroy
   respond_with(@category.destroy) do |format|
      format.html { redirect_to categories_path }
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
    def find_categoty
      @category = Category.find(params[:id])
    end
    def categories_load
      @categories = Category.find_each.map{ |c| [c.name, c.parent_id]}
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category, validate: true do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: "Category name" %>
  <%= f.button :submit, :class => 'btn-custom2' %>
<% end -%>

app/views/categories/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="row">
<h1>Country: <%= @country_name %></h1>
  <h2>Categories</h2>
   <ol class="tree"><%= just_tree @categories %></ol>
  <div class="col-md-7">
    <table class="table table-bordered table-striped">
      <tr>
        <th>Name:</th>
        <th>Edit</th>
        <th>Destroy</th>
    </tr>
    <% @categories.each do |category| %>
        <td><h4><%= category.name %></h4></td>
        <td><%= link_to "Edit", edit_category_path(category), :class => 'btn-custom2' %></td>
        <td><%= button_to "Delete", category , method: :delete, data: { confirm: "Are you sure?", }, :class => 'btn-custom2' %></td>
        </tr>
    <% end %>
  </table>
  <%= link_to "New category", new_category_path, class: 'btn-custom2' %>
</div>

app/views/categories/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>