config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  resources :orders, except: [:index, :show]
  devise_for :users
  resources :products do
    resources :reviews, except: [:index]
  end
  resources :cities do
    get 'search', on: :collection
  end

  get 'add_to' => "cities#add_to"
  delete 'delete' => "cities#delete"

  resources :line_items, except: [:index]
  resources :carts, except: [:index]
  resources :categories 
  root 'products#index'


 
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :category
  has_many :photos, as: :photoable
  has_many :reviews
  has_many :line_items

  default_scope -> { order "created_at" }
  scope :expensive_price, -> { where("price > 300")}


  validates :title, :category_id, presence: true
  before_destroy :ensure_not_referenced_by_any_line_item

  accepts_nested_attributes_for :photos
 
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end

  

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :categories_load, only: [:new, :edit, :create, :update]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update]
  
  respond_to :html, :js

  

  def index
    if params[:category].blank?
      @search = Product.ransack(params[:q])
      search_products(@search)
    else  
      @category_id = Category.find_by(name: params[:category]).id
      @search = Product.where(category_id: @category_id).ransack(params[:q])
      search_products(@search)
    end
    respond_with(@products)   
  end

  def show
    @reviews = @product.reviews.paginate(page: params[:page], per_page: 4)
    @average_review = Review.average_review(@product)
    respond_with(@product)  
  end

  def edit
   
  end

  def update
    @product.category_id = params[:category_id]
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    redirect_to root_url
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]
    if @product.save
      redirect_to root_url
    else
      render :new
    end
  end


  private

    def product_params
      params.require(:product).permit(:title, :description, :price, :category_id, photos_attributes: [:file])
    end
    def find_product
      @product = Product.find(params[:id])
    end
    def categories_load
      @categories = Category.find_each.map{ |c| [c.name, c.id]}
    end

    def search_products(search)
      @products = search.result.paginate(page: params[:page], per_page: 8).includes(:photos)
    end
 

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_nested_form_for @product, :html => { :multipart => true } do |f| %>
  <%= f.error_notification %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  <%= f.input :title, label: "Product Title" %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.fields_for :photos, @product.photos.build do |a| %>
    <%=  a.file_field :file, multiple: true, name: "product[photos_attributes][][file]" %>
   <% end %>
  <%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/products/_products.html.erb
 <div class="row">
  <h1 class="current-category"><%= params[:category] %></h1>
  <% if products.count == 0 %>
    <h3>Now don't have products in the category</h3>
  <% else %>
    <% products.each do |product| %>
     
     <div class="col-md-3">
        <h3> <%=  product.title%> </h1>
          <% unless product.photos.blank? %>
            <a href="/products/<%= product.id %>">
              <%= image_tag product.photos.first.file.url.to_s, class: "product" %> 
            </a>
          <% end %> 
          <h4 class="shop-now">
            <%= link_to "Shop now", product_path(product), :class => 'btn-custom' %>   
            <%= number_to_currency(product.price) %>
          </h4> 
      </div>
    <% end %>  
  <% end %>
</div>
<div class="container text-center">
  <div class="pagination">
    <%= will_paginate products, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/products/_review.html.erb
<div class="text-center">
    <h3>Reviews:</h3></br>
    <%= will_paginate review, renderer: BootstrapPagination::Rails %>
  </div>
 <% review.each do |r| %>
 <div class="review_<%= r.id %>">
  <div class="review">
    <div class="review-rating" data-score="<%= r.rating %>"></div>
    <p class="review-comment"><%= r.comment %></p>
    <% if user_signed_in? %>
      <% if r.user_id == current_user.id %>
        <div class="links btn-group">
          <%= link_to "Edit", edit_product_review_path(r.product, r), class: "btn btn-custom" %>
          <%= link_to "Delete", product_review_path(r.product, r), method: :delete, data: { confirm: "Are you sure?" }, remote: true, class: "btn btn-custom" %>
        </div>     
      <% end %> 
    <% end %>
  </div>
 </div> 
<% end %>
<%= render "reviews/form" %>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script


         

app/views/products/_search_form.html.erb
<% content_for :search do %>  
  <% search_form_for search, :builder => SimpleForm::FormBuilder, class: 'form-inline'  do |f| %>  
    <%= f.input_field :title_cont, class: "form-control", placeholder: 'Title..' %>
    <%= f.button :submit, "Search" %>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-product-form">

    <h1>Edit Product</h1>

    <%= simple_nested_form_for @product, :html => { :multipart => true } do |f| %>
      <%= f.error_notification %>
      <%= f.select :category_id, @categories %>
      <%= f.input :title, label: "Product Title" %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.fields_for :photos, @product.photos.build do |a| %>
        <%=  a.file_field :file, multiple: true, name: "product[photos_attributes][][file]" %>
        <% end %>
      <%= f.button :submit, :class => 'btn-custom2' %>
    <% end %>

  </div>

</div>

app/views/products/index.html.erb
<div id="products">
  <%= render "search_form", search: @search %>
  <%= render "products/products", products: @products %>
</div>
<script>
$(function(){
   $('.pagination a').attr('data-remote', 'true')
});
</script>

app/views/products/index.js.erb
$('#products').html("<%=  j render  'products/products', products: @products %>");
$('.pagination a').attr('data-remote', 'true');

app/views/products/new.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-product-form">

    <h1>New Product</h1>

    <%= render 'form' %>

  </div>

</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-4">
    <% unless @product.photos.blank? %>
      <%= image_tag @product.photos.first.file.url.to_s, class: "product-show" %>
      
        <% @product.photos.each do |p| %>
          <a href="/products/<%= @product.id %>">
          <%= image_tag p.file.url.to_s, class: "photo" %>
          </a>
        <% end %>
    <% end %> 
  </div>

  <div class="col-md-8">
    <div class="product-info">
      <h2> <%= @product.title %> </h2>
      <h4>Category: <br><%= @product.category.name %> </h4>
      <h2>Average Rating</h2>
      <% unless @average_review.nil? %>
        <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <% end %>
      <h4>Description: </h4>
      <h5> <%= @product.description %></h5>
      <h4>Price:</h4>
      <h4><%= number_to_currency(@product.price) %> </h4>
    </div>
  </div>
  <div class="add_to_cart">
     <%= button_to 'Add to Cart', line_items_path(product_id: @product),  class: "btn btn-custom" %>
  </div>
</div>
<% if  can?(:create, Product) %>
  <div class="admin-option">
    <%= link_to "Edit", edit_product_path(@product), class: "btn btn-custom" %>
    <%= link_to "Delete", product_path(@product), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
  </div>
<% end %>

  <div class="row">
    <div class="col-xs-11">
      <div class="reviews" id="reviewss">
        <%= render 'products/review', review: @reviews %>
         
      </div>  
    </div>
  </div> 
 


<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>
<script>
$(function(){
   $('.pagination a').attr('data-remote', 'true')
});
</script>

app/views/products/show.js.erb
$('#reviewss').html(" <%=  j render  'products/review', review: @reviews %>");
$('.pagination a').attr('data-remote', 'true');