config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  resources :orders, except: [:index, :show]
  devise_for :users
  resources :products do
    resources :reviews, except: [:index]
  end
  resources :cities do
    get 'search', on: :collection
  end

  get 'add_to' => "cities#add_to"
  delete 'delete' => "cities#delete"

  resources :line_items, except: [:index]
  resources :carts, except: [:index]
  resources :categories 
  root 'products#index'


 
end

app/models/ability.rb
class Ability
  include CanCan::Ability


 
  def initialize(user)
      
    user ||= User.new 
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
    end
    
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  # default_scope { where(joins(:line_items).order('line_items.quantity')) }
  
def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
      current_item.price = current_item.product.price
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set
  include TheSortableTree::Scopes

  default_scope -> { order 'lft ASC' } 
  has_many :products

  validates :name, presence: true

  before_destroy :ensure_not_referenced_by_any_product
  before_update :ensure_not_referenced_by_any_product

  def ensure_not_referenced_by_any_product
    if products.empty?
      return true
    else
      errors.add(:message, 'This Category has got products')
      return false
    end
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode 
  LOX = [ "VALUE", "CITY"]
 
  def self.get_cities_names(cities)
    array = []
    cities.each_pair {|key, value| array << value unless value.empty? }
    array
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  default_scope -> { order "price" }

  validates :quantity, numericality: { greater_than: 0 } 

  def total_price
    product.price * quantity    
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  validates :name, :address, :phone, presence: true
  validates :phone, numericality: true, length: { minimum: 9}
  
  
  def add_line_items(cart)
    cart.line_items.each do |line_item|
      line_item.cart_id = nil
      line_items << line_item
    end
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :photoable, polymorphic: true
  mount_uploader :file, PhotoUploader

end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :category
  has_many :photos, as: :photoable
  has_many :reviews
  has_many :line_items

  default_scope -> { order "created_at" }
  scope :expensive_price, -> { where("price > 300")}


  validates :title, :category_id, presence: true
  before_destroy :ensure_not_referenced_by_any_line_item

  accepts_nested_attributes_for :photos
 
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end

  

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  default_scope -> { order "created_at desc" }

  validates :rating, :comment, presence: true
  validates :product_id, uniqueness: {scope: :user_id,  message: "You already voted"}

   def self.average_review(product)
    average_review = 0 if product.reviews.blank?
    average_review ||= product.reviews.average(:rating).round(2)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews

  def role?(r)
    role.include? r.to_s
  end

  def self.found_country(ipaddress)
    geo = Maxminddb.lookup(ipaddress)
      if geo.found?
        geo.country.name
      end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  respond_to :js


  def show
    respond_with(@cart)
  end

  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    respond_with(@cart = Cart.create(cart_params))
  end

  def update
    @cart.update(cart_params)
    respond_with(@cart)
  end

  def destroy
    @cart.destroy
    redirect_to root_url
  end

  private

    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_url, notice: 'Invalid cart'
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  
  def new
    @city = City.new 
  end
  
  def create
    if params[:city][:cities_main][:city_first].blank?
      render :search
    else
      @cities_main = params[:city][:cities_main] 
      a =  City.get_cities_names(@cities_main) 
      @city = City.new(cities_name: a)
    respond_to do |format|
      if @city.save
        format.js   { @cities_name = @city.cities_name }
      else
        render :search
      end
    end
    end  
  end

  def search
    @city = City.new
    city = City.last
    @cities_name = city.cities_name
  end
  
  def add_to
    render layout: false
  end

  def delete
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "text-center alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, '×'.html_safe, class: 'close', data: {dismiss: 'alert'})
        concat message
      end)
      flash.clear
    end
    nil

  end
end

app/helpers/carts_helper.rb
module CartsHelper
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/render_tree_helper.rb
# DOC:
# We use Helper Methods for tree building,
# because it's faster than View Templates and Partials

# SECURITY note
# Prepare your data on server side for rendering
# or use h.html_escape(node.content)
# for escape potentially dangerous content
module RenderTreeHelper
  class Render
    class << self
      attr_accessor :h, :options

      def render_node(h, options)
        @h, @options = h, options

        node = options[:node]
        "
          <li>
            <div class='item'>
              #{ show_link }
            </div>
            #{ children }
          </li>
        "
      end

      def show_link
        node = options[:node]
        ns   = options[:namespace]
        url  = h.url_for(ns + [node])
        title_field = options[:title]

        "<h4>#{ h.link_to(node.send(title_field), url) }</h4>"
      end

      def children
        unless options[:children].blank?
          "<ol>#{ options[:children] }</ol>"
        end
      end

    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_cart_text.html.erb
<% if current_cart %>
  <div class="cart-top">
    <% unless current_cart.total_price == 0 %>
      <%= number_to_currency(current_cart.total_price) %>
      <%= link_to image_tag("http://simpleicon.com/wp-content/uploads/Shopping-Cart-10.png", size: "35x35"), cart_path(current_cart), class: "btn-custom" %>
    <% end %>
    </div>
<% end %>

app/views/layouts/_tree.html.erb
<% content_tag :li, :id => dom_id(menu) do %>
  <span class="handle"><%= menu.name %></span>    
  <% content_tag :ul do %>
   <% for child in menu.children do %>
    <%= render :partial => "tree", :locals => {:menu => child }%>
   <% end %>
  <% end unless menu.leaf? %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  <script src='//cdn.rawgit.com/googlemaps/js-rich-marker/gh-pages/src/richmarker-compiled.js' type='text/javascript'></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  <script src='//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.0/additional-methods.min.js' type='text/javascript'></script>
 
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">

    <div class="container">

      <div class="navbar-header">
        <div class="logo">
          <%= link_to "The Laura", root_path, class: "navbar-brand" %>
        </div>
      </div>

      <ul class="nav navbar-nav">
        <div class="user-panel">
         <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "btn btn-link"  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-link"  %> or <%= link_to "sign in", new_user_session_path, class: "btn btn-link"  %>
        <% end %>
        </div>
      </ul>
      <div class="col-md-5">
        <div class="search">
          <%= yield(:search) %>
        </div>
      </div>
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, products_path(category: category.name), class: "link" %>
              </li>
            <% end %>
          </ul>
        </li>
        
        <li id="test"><%= render 'layouts/cart_text' %> </li>
        
      </ul>

    </div>

  </nav>
  <div class="container text-center">
    <%= flash_messages %>
  </div>
  <div class="container">     
<%= yield %>
</div>

</body>
</html>

app/views/order_notifier/received.html.erb
<h1>New order</h1>
<p>
  <h3><%= @order.name %></h3>
  <h3><%= @order.phone %></h3>
  <h4>Details:</h4>
  <% @order.line_items.each do |item| %>
        <td><h4><%= item.product.title %></h4></td>
        <td><h4><%= item.total_price %></h4></td>
        <td><h4><%= item.quantity %></h4></td>
  <% end %>
</p>